project_id = "fgvjvtglcmxzadetmmoi"

[functions.chargers-api]
verify_jwt = false

[functions.charger-commands]
verify_jwt = false

[functions.transactions-api]
verify_jwt = false

[functions.wallet-api]
verify_jwt = false

[functions.ocpp-diagnostics]
verify_jwt = false
