// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { customStorage } from './storage';

const SUPABASE_URL = "https://fgvjvtglcmxzadetmmoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZndmp2dGdsY214emFkZXRtbW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNDkzNTksImV4cCI6MjA3NDgyNTM1OX0.w1jH2DHoWnQwyxpG7HQYie3gMX5XN2GEz_7E7n0p6H0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: customStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});